### PR TITLE
Fix a typo and format README with prettier

### PR DESCRIPTION
**Pull request by dr460nf1r3**

### CODE REVIEW

**Comment by msrd0** [comment]
I don't see why this PR should be accepted. The formatting changes are 90% useless. And honestly, toml with one space indentation looks super weird. I've never seen another Rust project use one space indentation. Whatever prettier wants is super irrelevant for Rust projects anyways.

I'll let @LuckyTurtleDev decide but I vote to close this.

**Comment by dr460nf1r3** [comment]
It's your choice, I can remove that since this was about the typo mostly anyways.

**Comment by msrd0** [comment]
Fixing typos is always appreciated of course :) Doing weird formatting changes with questionable benefits not so much

**Comment by LuckyTurtleDev** [comment]
I do not see much advance in merging this. But thanks for your efforts.

**Pull request closed without merging**
